BLOCK modc18

FIELDS
    stimestamp, etimestamp : TIMETYPE
    sdatestamp, edatestamp : DATETYPE
    C1801 "Any kind of meat (cow / rabbit / sheep / goat / pig).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF MEAT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Aina yoyote ya nyama (ng'ombe / sungura / kondoo / nguruwe).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF MEAT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1802 "Any kind of poultry meat (chicken / duck / turkey).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF POULTRY MEAT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Aina yoyote ya nyama ya ndege (kuku / bata / bata mzinga).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF POULTRY MEAT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1803 "Any kind of fresh fish.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF FRESH FISH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Aina yoyote ya samaki mbichi.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF FRESH FISH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1804 "Any kind of dried fish (Omena / obambla).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF DIRED FISH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Aina yoyote ya samaki iliyokaushwa (Omena / obambla).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY KIND OF DRIED FISH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1805 "Termites.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY TERMITES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Kumbikumbi.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY TERMITES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1806 "Eggs.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY EGGS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Mayai.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY EGGS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1807 "Milk.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS DRANK MILK OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Maziwa.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS DRANK MILK OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1808 "Yogurt / Home-made clotted milk / Maziwa Mala.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY YOGURT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Yogurt / Maziwa ya kuganda / Maziwa Mala.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY YOGURT OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1809 "Beans, cowpeas, green grams and other legumes.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY LEGUMES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Maharagwe, pojo, ndengu na legumes zinginezo.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY LEGUMES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1810 "Peanuts (groundnuts) and other nuts.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY NUTS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Njugu na zinginezo za aina hiyo.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY NUTS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1811 "Orange flesh sweet potato.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY SWEET POTATOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Viazi vitamu vya manjano.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY SWEET POTATOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1812 "Pumpkins / orange, butternut or yellow squash.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PUMPKINS / ORANGE, BUTTERNUT OR YELLOW SQUASH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Malenge / squash ya rangi ya manjano au butternut au ya machungwa.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PUMPKINS / ORANGE, BUTTERNUT OR YELLOW SQUASH OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1813 "Dark green leafy vegetables (Sukuma wiki / Chisaga / Managu / Kunde / Dodo / Mrenda).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY DARK GREEN LEAFY VEGETABLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Mboga yenye matawi ya kijani (Sukuma wiki / Chisaga / Managu / Kunde / Dodo / Mrenda).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY DARK GREEN LEAFY VEGETABLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1814 "Red leafy vegetables.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY RED LEAFY VEGETABLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Mboga yenye matawi nyekundu.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY RED LEAFY VEGETABLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1815 "Mango.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY MANGOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Maembe.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY MANGOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1816 "Guava.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY GUAVAS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Mapera.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY GUAVAS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1817 "Pineapple.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PINEAPPLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Nanasi.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PINEAPPLES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1818 "Pawpaw (Papaya).
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PAWPAWS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Paipai.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY PAWPAWS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1819 "Banana.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY BANANAS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Ndizi.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY BANANAS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1820 "Avocado.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY AVOCADOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Avokado.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY AVOCADOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1821 "Tomato.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY TOMATOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Nyanya.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY TOMATOES OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK
    C1822 "Ant hill soil, brick, soft stones, earthen wall / mud walls.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY ANT HILL SOIL, BRICK, SOFT STONES, EARTHEN WALL / MUD WALLS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          "Kichuguu, matofali, mawe, udongo wa ukuta.
          @/@/@RYOU CAN SELECT @BDon't Know@B BY GOING TO @BAnswer@B >> @BDon't Know@B FROM THE MENU, OR PRESSING THE SHORTCUT KEYS @BCtrl+K@B IF THE RESPONDENT DOES NOT KNOW IF SHE HAS EATEN ANY ANT HILL SOIL, BRICK, SOFT STONES, EARTHEN WALL / MUD WALLS OR NOT
          @/@/YOU CAN ENTER THE VALUE @R@B“66”@B@R IF THE RESPONDENT HAS EATEN BUT DOES NOT KNOW HOW MANY DAYS@R"
          : 0..66, DK

AUXFIELDS
    aux_c18 "@G@BModule 18@|7 - Day Food Frequency Questionnaire for Mothers (MOTHER OF STUDY CHILD)@B@G" : (ENTER), EMPTY
    aux_C1801 "@GIn the past 7 days, that is last seven days (since this day last week), on how many days have you eaten the following foods:@G"
              "@GKwa siku 7 zilizopita, (tangu leo wiki iliyopita), ni siku ngapi ulikula vyakula vifuatavyo:@G"
              : (ENTER), EMPTY
LAYOUT
    BEFORE aux_c18 NEWPAGE
    AFTER aux_c18 NEWPAGE

RULES
    aux_c18

    {START TIME AND DATE STAMPS}
    stimestamp.KEEP
    IF ((stimestamp = EMPTY) AND (C1801 = RESPONSE)) THEN
        stimestamp:= SYSTIME
    ENDIF
    sdatestamp.KEEP
    IF sdatestamp = EMPTY THEN
        sdatestamp:= SYSDATE
    ENDIF

    {BEGIN}

    aux_C1801
    C1801
    CHECK ((C1801 < 8) OR (C1801 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1802
    CHECK ((C1802 < 8) OR (C1802 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1803
    CHECK ((C1803 < 8) OR (C1803 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1804
    CHECK ((C1804 < 8) OR (C1804 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1805
    CHECK ((C1805 < 8) OR (C1805 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1806
    CHECK ((C1806 < 8) OR (C1806 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1807
    CHECK ((C1807 < 8) OR (C1807 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1808
    CHECK ((C1808 < 8) OR (C1808 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1809
    CHECK ((C1809 < 8) OR (C1809 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1810
    CHECK ((C1810 < 8) OR (C1810 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1811
    CHECK ((C1811 < 8) OR (C1811 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1812
    CHECK ((C1812 < 8) OR (C1812 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1813
    CHECK ((C1813 < 8) OR (C1813 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1814
    CHECK ((C1814< 8) OR (C1814 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1815
    CHECK ((C1815 < 8) OR (C1815 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1816
    CHECK ((C1816 < 8) OR (C1816 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1817
    CHECK ((C1817 < 8) OR (C1817 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1818
    CHECK ((C1818 < 8) OR (C1818 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1819
    CHECK ((C1819 < 8) OR (C1819 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1820
    CHECK ((C1820 < 8) OR (C1820 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1821
    CHECK ((C1821 < 8) OR (C1821 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    C1822
    CHECK ((C1822 < 8) OR (C1822 > 65)) "@R@BERROR!@B
                                        @/@/Please enter a value between @B1@B and @B7@B unless you want to enter the special code @B66@B.@R"
    {FINISH}

    {END TIME AND DATE STAMPS}
    etimestamp.KEEP
    IF ((etimestamp = EMPTY) AND (C1822 = RESPONSE)) THEN
        etimestamp:= SYSTIME
    ENDIF
    edatestamp.KEEP
    IF (edatestamp = EMPTY) THEN
        edatestamp:= SYSDATE
    ENDIF
ENDBLOCK
